openapi: "3.0.2"

info:
  version: 1.0.0
  title: sample api

paths:
  /items:
    get:
      summary: List all items
      responses:
        '200':
          description: List all items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"

components:
  schemas:
    Item:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          type: string